name: admin
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  provider: ^6.1.2
  file_picker: ^10.2.0
  fl_chart: ^1.0.0
  image_picker_for_web: ^3.0.4
  shared_preferences: ^2.2.2
  geocoding: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/